import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main styles={styles.main}>
        <Link href={"/type/csr"}>Client Side Render</Link>
        <Link href={"/type/ssr"}>Server Side Render</Link>
        <Link href={"/type/ssg"}>Server Side Render</Link>
      </main>
    </div>
  );
}
